travelblog/main/urls.py
from django.urls import path

from .views import *

app_name = 'main'
urlpatterns = [
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('account/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('account/register/', RegisterUserView.as_view(), name='register'),
    path('account/login/', ArticleLoginView.as_view(), name='login'),
    path('account/logout/', ArticleLogoutView.as_view(), name='logout'),
    path('account/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('account/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('account/profile/change/<int:pk>/', profile_article_change, name='profile_bb_change'),
    path('account/profile/delete/<int:pk>/', profile_article_delete, name='profile_bb_delete'),
    path('account/profile/add/', profile_article_add, name='profile_bb_add'),
    path('account/profile/<int:pk>/', profile_article_detail, name='profile_bb_detail'),
    path('account/profile/', profile, name='profile'),
    path('account/password/change/', ArticlePasswordChangeView.as_view(), name='password_change'),
    path('', index, name='index'),

]

travelblog/travelblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelblog/main/models.py
from django.contrib.auth.models import User
from django.db import models


from .utilities import get_timestamp_path

#  рубрика
class Rubric(models.Model):
    name = models.CharField(max_length=225, db_index=True, unique=True, verbose_name='Name')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Order')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT,
                                     null=True, blank=True, verbose_name='Super_rubric')


#  надрубрика
class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SuperRubric(Rubric):
    object = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = 'Sub_rubric'
        verbose_name_plural = 'Sub_rubrics'


#  подрубрика
class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)


class SubRubric(Rubric):
    object = SubRubricManager()

    def __str__(self):
        return '%s: %s' % (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name')
        verbose_name = 'Sub_rubric'
        verbose_name_plural = 'Sub_rubrics'


#  дополнительные иллюстрации
class AdditionalImage(models.Model):
    bb = models.ForeignKey('Article', on_delete=models.CASCADE, verbose_name='The note')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Image')

    class Meta:
        verbose_name = 'Additional Image'
        verbose_name_plural = 'Additional Images'


#  объявление
class Article(models.Model):
    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT, verbose_name='Rubric')
    title = models.CharField(max_length=255, verbose_name='Title')
    content = models.TextField(verbose_name='Content')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Show?')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Image')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['-created_at']

travelblog/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from .models import *


# личные данные пользователя
class ChangeUserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')


# регистрация пользователя
class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name')


#  форма надрубрики
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(
        queryset=SubRubric.object.all(), empty_label=None, label='Super_rubric', required=False)

    class Meta:
        model = SubRubric
        fields = '__all__'


# форма поиска по контексту
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=50, label='')


# форма добавления записи и набор форм
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = ['rubric', 'title', 'content', 'is_active', 'image']
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Article, AdditionalImage, fields='__all__')

travelblog/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView

from .forms import *
from .models import *


# О сайте
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


# Вход пользователя на сайт
class ArticleLoginView(SuccessMessageMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'main/login.html'
    success_message = 'You have successfully sign in'


# Выход
class ArticleLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


# Смена данных пользователя
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Personal data has been successfully changed'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# Смена пароля
class ArticlePasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'User password changed successfully'


# Регистрация пользователя
class RegisterUserView(CreateView):
    model = User
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


# Удаление пользователя
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')


    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# список всех записей по рубрикам меню (динамическая)
def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Article.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'rubric': rubric,
        'page': page,
        'bbs': page.object_list,
        'form': form,
    }

    return render(request, 'main/by_rubric.html', context)

# Список записей пользователя
@login_required
def profile(request):
    bbs = Article.objects.filter(author=request.user.pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'bbs': page.object_list,
               'page': page,
               'paginator': paginator,
               'form': form}

    return render(request, 'main/profile.html', context)


# Главная
def index(request):
    bbs = Article.objects.filter(is_active=True)[:10]
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'bbs': page.object_list,
        'page': page,
        'form': form,
    }
    return render(request, 'main/index.html', context)


# общая страница просмотра записи
def detail(request, rubric_pk, pk):
    bb = get_object_or_404(Article, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail.html', context)


# страница просмотра записи для пользователя
def profile_article_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Article, pk=pk, author=request.user.pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail_article_detail.html', context)


# добавление записи
@login_required
def profile_article_add(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                return redirect('main:profile')
    else:
        form = ArticleForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_article_add.html', context)


# редактирование записи
@login_required
def profile_article_change(request, pk):
    bb = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                return redirect('main:profile')
    else:
        form = ArticleForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_article_change.html', context)


# удаление записи
@login_required
def profile_article_delete(request, pk):
    bb = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        bb.delete()
        return redirect('main:profile')
    else:
        context = {'bb': bb, }
        return render(request, 'main/profile_article_delete.html', context)

travelblog/main/templates/main/about.html
{% extends 'layout/basic.html' %}

{% block title %}О сайте{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>О сайте</h2>
            <p>Сайт для публикаций</p>
            <p>Все права принадлежат &laquo;Django 3.0&raquo;</p>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/by_rubric.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block content %}

<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
            <form class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %}
                {% buttons submit='Search' %}{% endbuttons %}
            </form>
    </div>
    <div class="row">
        <div class="col">
            <h2>{{ rubric }}</h2>
            {% if bbs %}
            <ul class="list-unstyled">
                {% for bb in bbs %}
                <li class="media my-2 p-2 border">
                    {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                        <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                        {% else %}
                        <img class="mr-3" src="{% static 'main/bg.jpg' %}">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <p class="text-right font-italic">{{ bb.created_at }}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% bootstrap_pagination page url=keyword %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/change_user_info.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Profile of {{ user.username }}</h2>
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons submit='Change' %}{% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/delete_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Delete user{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Delete user {{ object.username }}</h2>
            <form method="post">
                {% csrf_token %}
                {% buttons submit='Delete' %}{% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/detail.html
{% extends 'layout/basic.html' %}

{% block title %}{{ bb.title }} - {{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <p><a class='btn btn-primary' href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}">Back</a></p>
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto">
            <img src="{{ bb.image.url }}" class="main-image">
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content|linebreaks }}</p>
            <p class="text-right font-italic">Created {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="container-fluid border shadow">
    <div class="row">
        <div class="d-flex justify-content-between flex-wrap mt-3 thumb">
            {% for ai in ais %}
            <div>
                <a data-fancybox="gallery" href="{{ ai.image.url }}">
                    <img class="additional-image" src="{{ ai.image.url }}" alt="">
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

travelblog/main/templates/main/detail_article_detail.html
{% extends 'layout/basic.html' %}

{% block title %}{{ bb.title }} - {{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <p>detail__bb__detail</p>
    <p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}">Backward</a></p>
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto">
            <img src="{{ bb.image.url }}" class="main-image">
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content|linebreaks }}</p>
            <p class="text-right font-italic">Created {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div class="row border shadow">
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}


{% endblock %}

travelblog/main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Main{% endblock %}
{% block content %}


<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp</div>
            <form class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %}
                {% buttons submit='Search' %}{% endbuttons %}
            </form>
    </div>
    <div class="row">
        <div class="col">
            <h2>The last notes</h2>
            {% if bbs %}
            <ul class="list-unstyled">
                {% for bb in bbs %}
                <li class="media my-2 p-2 border">
                    {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                        <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                        {% else %}
                        <img class="mr-3" src="{% static 'main/2_32x32.png' %}">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <p class="text-right font-italic">{{ bb.created_at }}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% bootstrap_pagination page url=keyword %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/login.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Sign in{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Sign in</h2>
            {% if user.is_authenticated %}
            <p>You have successfully sign in</p>
            {% else %}
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                <input type="hidden" name="next" value="{{ next }}"/>
                {% buttons submit='Sing in' %}{% endbuttons %}
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/logout.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Logout{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Logout</h2>
            <p>You have successfully logout</p>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/password_change.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Change password{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Change password of {{ user.username }}</h2>
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons submit='Change password' %}{% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/profile.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}My notes{% endblock %}

{% block content %}
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
            <form class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %}
                {% buttons submit='Search' %}{% endbuttons %}
            </form>
    </div>
    <div class="row">
        <div class="col">
            <h2>Notes of {{ user.username }}</h2>
            <p><a class='btn btn-primary' href="{% url 'main:profile_bb_add' %}">Add new note</a></p>
            {% if bbs %}
            <ul class="list-unstyled">
                {% for bb in bbs %}
                <li class="media my-2 p-2 border">
                    {% url 'main:detail_bb_detail' rubric_pk=rubric.pk pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                        <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                        {% else %}
                        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <p class="text-right font-italic">{{ bb.created_at }}</p>
                        <p class="text-right mt-2">
                            <a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Change</a>
                            | <a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Delete</a>
                        </p>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% bootstrap_pagination page url=keyword %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/profile_article_add.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Add note{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Add new note</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% bootstrap_formset formset layout='horizontal' %}
                {% buttons submit='Add new' %}{% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/profile_article_change.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Change a note{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Change a note</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% bootstrap_formset formset layout='horizontal' %}
                {% buttons submit='Change' %}{% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

travelblog/main/templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% block title %}Success{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Create a profile</h2>
            <p>You have successfully created a profile</p>
        </div>
    </div>
</div>
{% endblock %}