travelblog/main/urls.py
from django.urls import path

from .views import *

app_name = 'main'
urlpatterns = [
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('account/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('account/register/', RegisterUserView.as_view(), name='register'),
    path('account/login/', ArticleLoginView.as_view(), name='login'),
    path('account/logout/', ArticleLogoutView.as_view(), name='logout'),
    path('account/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('account/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('account/profile/change/<int:pk>/', profile_article_change, name='profile_bb_change'),
    path('account/profile/delete/<int:pk>/', profile_article_delete, name='profile_bb_delete'),
    path('account/profile/add/', profile_article_add, name='profile_bb_add'),
    path('account/profile/<int:pk>/', profile_article_detail, name='profile_bb_detail'),
    path('account/profile/', profile, name='profile'),
    path('account/password/change/', ArticlePasswordChangeView.as_view(), name='password_change'),
    path('', index, name='index'),

]

travelblog/travelblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelblog/main/models.py
from django.contrib.auth.models import User
from django.db import models


from .utilities import get_timestamp_path

#  рубрика
class Rubric(models.Model):
    name = models.CharField(max_length=225, db_index=True, unique=True, verbose_name='Name')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Order')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT,
                                     null=True, blank=True, verbose_name='Super_rubric')


#  надрубрика
class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SuperRubric(Rubric):
    object = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = 'Sub_rubric'
        verbose_name_plural = 'Sub_rubrics'


#  подрубрика
class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)


class SubRubric(Rubric):
    object = SubRubricManager()

    def __str__(self):
        return '%s: %s' % (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name')
        verbose_name = 'Sub_rubric'
        verbose_name_plural = 'Sub_rubrics'


#  дополнительные иллюстрации
class AdditionalImage(models.Model):
    bb = models.ForeignKey('Article', on_delete=models.CASCADE, verbose_name='The note')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Image')

    class Meta:
        verbose_name = 'Additional Image'
        verbose_name_plural = 'Additional Images'


#  объявление
class Article(models.Model):
    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT, verbose_name='Rubric')
    title = models.CharField(max_length=255, verbose_name='Title')
    content = models.TextField(verbose_name='Content')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Show?')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Image')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['-created_at']

travelblog/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from .models import *


# личные данные пользователя
class ChangeUserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')


# регистрация пользователя
class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name')


#  форма надрубрики
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(
        queryset=SubRubric.object.all(), empty_label=None, label='Super_rubric', required=False)

    class Meta:
        model = SubRubric
        fields = '__all__'


# форма поиска по контексту
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=50, label='')


# форма добавления записи и набор форм
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = ['rubric', 'title', 'content', 'is_active', 'image']
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Article, AdditionalImage, fields='__all__')

travelblog/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView

from .forms import *
from .models import *


# О сайте
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


# Вход пользователя на сайт
class ArticleLoginView(SuccessMessageMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'main/login.html'
    success_message = 'You have successfully sign in'


# Выход
class ArticleLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


# Смена данных пользователя
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Personal data has been successfully changed'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# Смена пароля
class ArticlePasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'User password changed successfully'


# Регистрация пользователя
class RegisterUserView(CreateView):
    model = User
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


# Удаление пользователя
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')


    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# список всех записей по рубрикам меню (динамическая)
def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Article.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'rubric': rubric,
        'page': page,
        'bbs': page.object_list,
        'form': form,
    }

    return render(request, 'main/by_rubric.html', context)

# Список записей пользователя
@login_required
def profile(request):
    bbs = Article.objects.filter(author=request.user.pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'bbs': page.object_list,
               'page': page,
               'paginator': paginator,
               'form': form}

    return render(request, 'main/profile.html', context)


# Главная
def index(request):
    bbs = Article.objects.filter(is_active=True)[:10]
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'bbs': page.object_list,
        'page': page,
        'form': form,
    }
    return render(request, 'main/index.html', context)


# общая страница просмотра записи
def detail(request, rubric_pk, pk):
    bb = get_object_or_404(Article, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail.html', context)


# страница просмотра записи для пользователя
def profile_article_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Article, pk=pk, author=request.user.pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail_article_detail.html', context)


# добавление записи
@login_required
def profile_article_add(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                return redirect('main:profile')
    else:
        form = ArticleForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_article_add.html', context)


# редактирование записи
@login_required
def profile_article_change(request, pk):
    bb = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                return redirect('main:profile')
    else:
        form = ArticleForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_article_change.html', context)


# удаление записи
@login_required
def profile_article_delete(request, pk):
    bb = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        bb.delete()
        return redirect('main:profile')
    else:
        context = {'bb': bb, }
        return render(request, 'main/profile_article_delete.html', context)

travelblog/main/templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wigth=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Main{% endblock %}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}

    <!-- fancyBox CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />

</head>
<body class="container-fluid bg-light">
    <header class="mb-4">
        <h1 class="display-4 text-center">Personal traveling</h1>
    </header>
    <div class="row bg-warning shadow">
        <ul class="col nav justify-content-end">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-item dropdown-toggle"
                   data-toggle="dropdown"
                   href="#" role="button" aria-haspopup="true"
                   aria-expanded="false">Personal Area: {{ user.username }}</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'main:profile' %}">My notes</a>
                    <a class="dropdown-item" href="{% url 'main:profile_change' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'main:password_change' %}">Сhange password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Delete profile</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'main:register' %}">Create profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Sign in</a> </li>
            {% endif %}
        </ul>
    </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border shadow">
                <a class="nav-link root" href="{% url 'main:index' %}">Main</a>

                {% for rubric in rubrics %}
                    {% ifchanged rubric.super_rubric.pk %}
                    <span class="'nav-link root font-weight-bold">{{ rubric.super_rubric.name }}</span>
                    {% endifchanged %}
                        {% if rubric.super_rubric.pk %}
                        <a class="nav-link" href="{% url 'main:by_rubric' pk=rubric.pk %}">{{ rubric.name }}</a>
                        {% endif %}
                {% endfor %}
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">About us</a>
            </nav>
            <section class="col border py-2 shadow">
<!--                {% bootstrap_messages %}-->
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; Alata</p>
        </footer>

<!--    библиотеки fancybox-->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    </body>
</html>